# -*- coding: utf-8 -*-
"""Untitled51.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LrLnDFaHkHBqTwTUMUw7dvZOOth8Z6n8
"""

stock_prices = {
    "AAPL": 189,
    "TSLA": 258,
    "GOOG": 130,
    "MSFT": 345,
    "AMZN": 134
}

portfolio = {}
total = 0

print("Enter your stock and quantity (type 'done' to finish):")

while True:
    stock = input("Stock symbol: ").upper()
    if stock == 'DONE':
        break
    if stock not in stock_prices:
        print("Stock not found. Try again.")
        continue
    qty = int(input("Quantity: "))
    portfolio[stock] = portfolio.get(stock, 0) + qty

print("\nYour Portfolio:")
for stock, qty in portfolio.items():
    value = stock_prices[stock] * qty
    total += value
    print(f"{stock}: {qty} shares = ${value}")

print(f"\nTotal Investment: ${total}")